https:
  enabled: false
  fullchain: 
  privkey:   
mongo: 
  dropFirst: false
  uri: "mongodb://localhost:27017"
logging: 
  loki: 
    host: 
    port: 
mail: 
  enabled: false
  smtp: 
    host: 
    port: 
    from: 
    pwd: 
  sendTo: 
  