name: Run tests with coverage 

on:
  push:
    branches-ignore:
      - production
  pull_request:
    branches-ignore:
      - production

env: 
  MONGO_VERSION: 5.0.1

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Lint code
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41.1
        args: --timeout 2m0s

    - name: Vet code
      run: go vet ./...

    - name: Download MongoDB and setup standalone db
      run: |
        wget --quiet http://downloads.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-$MONGO_VERSION.tgz
        tar xzvf mongodb-linux-x86_64-ubuntu2004-$MONGO_VERSION.tgz
        echo "$PWD/mongodb-linux-x86_64-ubuntu2004-$MONGO_VERSION/bin" >> $GITHUB_PATH
        mkdir $PWD/db
        mongod --dbpath $PWD/db --logpath /dev/null --nojournal --fork

    - name: Run test
      run: ./test.sh
    
    - name: Export coverage result 
      run: bash <(curl -s https://codecov.io/bash)
