name: Run tests with coverage 

on:
  push:
    branches-ignore:
      - production
  pull_request:
    branches-ignore:
      - production

env: 
  MONGO_VERSION: 6.0.0
  UBUNTU_VERSION: linux-x86_64-ubuntu2004

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - name: Lint code 
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.47.1
        args: --timeout 2m0s

    - name: Vet code
      run: go vet ./...

    - name: Download MongoDB and setup standalone db
      run: |
        wget --quiet http://downloads.mongodb.org/linux/mongodb-$UBUNTU_VERSION-$MONGO_VERSION.tgz
        tar xzvf mongodb-$UBUNTU_VERSION-$MONGO_VERSION.tgz
        echo "$PWD/mongodb-$UBUNTU_VERSION-$MONGO_VERSION/bin" >> $GITHUB_PATH
        mkdir $PWD/db
        mongod --dbpath $PWD/db --logpath /dev/null --nojournal --fork

    - name: Run test
      run: ./test.sh
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.txt