name: Run tests with coverage 

on:
  push:
    branches-ignore:
      - production
  pull_request:
    branches-ignore:
      - production

env: 
  MONGO_VERSION: 6.0.2
  UBUNTU_VERSION: linux-x86_64-ubuntu2004
  ESBUILD_VERSION: 0.14.11

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Check minified files
      id: check_minified_files
      run: |
        go install github.com/evanw/esbuild/cmd/esbuild@v$ESBUILD_VERSION
        ./bundle.sh
        git diff --quiet

    - name: Print message if files are out of sync
      if: failure() && steps.check_minified_files.outcome == 'failure'
      run: echo "minified files are out of sync, run ./bundle.sh and commit the modified files"

    - name: Lint code 
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.48.0
        args: --timeout 2m0s

    - name: Vet code
      run: go vet ./...

    - name: Download MongoDB and setup standalone db
      run: |
        wget --quiet http://downloads.mongodb.org/linux/mongodb-$UBUNTU_VERSION-$MONGO_VERSION.tgz
        tar xzvf mongodb-$UBUNTU_VERSION-$MONGO_VERSION.tgz
        echo "$PWD/mongodb-$UBUNTU_VERSION-$MONGO_VERSION/bin" >> $GITHUB_PATH
        mkdir $PWD/db
        mongod --dbpath $PWD/db --logpath /dev/null --nojournal --fork

    - name: Run test
      run: ./test.sh
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.txt